# Generated by Django 3.0.7 on 2020-07-18 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=100)),
                ('subject', models.IntegerField(choices=[(1, 'English'), (2, 'Programming'), (3, 'Mathematics'), (4, 'Others')], default=None, verbose_name='科目')),
                ('content', models.TextField(default=None, null=True)),
                ('study_time', models.FloatField(blank=True, default=0, null=True)),
                ('images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
